addons:
  apt:
    packages:
    - latex-beamer
    - latex-xcolor
    - texlive
    - texlive-base
    - texlive-binaries
      #- texlive-common
      #- texlive-doc-base
    - texlive-extra-utils
    - texlive-font-utils
    - texlive-fonts-recommended
    - texlive-generic-recommended
    - texlive-lang-german
    - texlive-latex-base
    - texlive-latex-extra
    - texlive-latex-recommended
    - texlive-luatex
    - texlive-pictures
    - texlive-pstricks
    - texlive-xetex
    - fonts-linuxlibertine
    - lmodern
script:
  - xelatex -synctex=1 -interaction=nonstopmode --quiet erstiheft_gesamt.tex || /bin/true
sudo: false
dist: trusty
branches:
  only:
    - master
env:
  secure: "YHx7eSvHg/7UTU6GAFLaTgKYnIDxU6Pcy09EaQW8SmdH+tZqNx+3LY+zkeBX2diHy0roFLuGAKe4kpShIRRmvS7yzTQA9k5ZyLBykUxvQQSblA/mdm9mt7eZuf+JZPbu88dkO85oZHI7qnA95/Qw7Hr8gC+alfK87CyY9PGTW/pYUqw6Imv+HswEHdT5/7Z84fxiBIUrJvPtiz1uhbKtirgQC6DOJmG/YzLJBo/3a0CXDqgBAnJg4qvDeGz3apegvnuWmcOJ0Wn/LyCNhm213uQWQlEx2lVgkcekpL7P5IXmVm8Pnj9xfedwIz0uRJ6KS/94cLaHhfffEr1fbWi+w8/hxqJmxoAUq8wBx2A1HOTfxkyVtMtd8arZGoN3KdhY0O73Z3KUgrDf8tZxEumF+L6FmlGSa7FjlVSDp3qpU++ltw0Zkabg8RLA/1sPH3dCMSxvrtmiiLqJTekXtFOn6zCaifyj+b59uFrtu9M3SxbTnflIZPBgJWkJlqn+rMr0uQZ2GSzqOdzXm6LJyTdN7MZ9WrcWYnHdyecjafS+B/xPmzq9gH4kIM+VnRN4B90G87Pwl+6aHbSMI2DtWLgpMcOEW6lMxHlMwjhX1DsueGlI5u4qMFnyL2pp14ZspqVYfhD+NL6w7mc+FsLWLwiHtA1r32p0TjxF2s4Abuj1pQU="
deploy:
  skip_cleanup: true
  provider: script
  script: ./deploy_to_ghpages.sh
